"""
This type stub file was generated by pyright.
"""

import os
from typing import BinaryIO, TYPE_CHECKING, overload
from barcode.codabar import CODABAR
from barcode.codex import Code128, Code39, Gs1_128, PZN
from barcode.ean import EAN13, EAN13_GUARD, EAN14, EAN8, EAN8_GUARD, JAN
from barcode.errors import BarcodeNotFoundError
from barcode.isxn import ISBN10, ISBN13, ISSN
from barcode.itf import ITF
from barcode.upc import UPCA
from barcode.version import version
from barcode.base import Barcode
from barcode.writer import BaseWriter

"""This package provides a simple way to create standard barcodes.
It needs no external packages to be installed, the barcodes are
created as SVG objects. If Pillow is installed, the barcodes can also be
rendered as images (all formats supported by Pillow).
"""
if TYPE_CHECKING:
    ...
__BARCODE_MAP: dict[str, type[Barcode]] = ...
PROVIDED_BARCODES = ...
@overload
def get(name: str, code: str, writer: BaseWriter | None = ..., options: dict | None = ...) -> Barcode:
    ...

@overload
def get(name: str, code: None = ..., writer: BaseWriter | None = ..., options: dict | None = ...) -> type[Barcode]:
    ...

def get(name: str, code: str | None = ..., writer: BaseWriter | None = ..., options: dict | None = ...) -> Barcode | type[Barcode]:
    """Helper method for getting a generator or even a generated code.

    :param name: The name of the type of barcode desired.
    :param code: The actual information to encode. If this parameter is
        provided, a generated barcode is returned. Otherwise, the barcode class
        is returned.
    :param Writer writer: An alternative writer to use when generating the
        barcode.
    :param options: Additional options to be passed on to the barcode when
        generating.
    """
    ...

def get_class(name: str) -> type[Barcode]:
    ...

def generate(name: str, code: str, writer: BaseWriter | None = ..., output: str | os.PathLike | BinaryIO | None = ..., writer_options: dict | None = ..., text: str | None = ...) -> str | None:
    """Shortcut to generate a barcode in one line.

    :param name: Name of the type of barcode to use.
    :param code: Data to encode into the barcode.
    :param writer: A writer to use (e.g.: ImageWriter or SVGWriter).
    :param output: Destination file-like or path-like where to save the generated
     barcode.
    :param writer_options: Options to pass on to the writer instance.
    :param text: Text to render under the barcode.
    """
    ...

get_barcode = ...
get_barcode_class = ...
