import { useCallback, useEffect, useState, type ChangeEvent, type CSSProperties, type FormEvent } from 'react';
import { Activity, ArrowLeft, ArrowRight, BarChart3, Bell, Calculator, Check, CheckCircle2, ChevronRight, CircleDollarSign, Clock3, CreditCard, Dumbbell, FileText, LayoutDashboard, LogIn, LogOut, Radio, RefreshCw, Search, ShieldCheck, Sparkles, Target, UserCheck, Users, Wallet, X, Zap } from 'lucide-react';
import { QRCodeSVG } from 'qrcode.react';
import { useDB, usePolling, type AttendanceLog, type Billing, type Member, type PendingApproval, type Expense } from './lib/database';

type View = 'home' | 'admin' | 'portal' | 'kiosk';
type AdminTab = 'overview' | 'approvals' | 'members' | 'billing' | 'expenses' | 'ai';

const money = (value: number | null | undefined) => `₹${(value ?? 0).toLocaleString('en-IN')}`;
const daysLeft = (expiry: string | null) => expiry ? Math.max(0, Math.ceil((new Date(expiry).getTime() - Date.now()) / 86400000)) : 0;
const todayStr = () => new Date().toISOString().slice(0, 10);

export default function App() {
  const [view, setView] = useState<View>('home');
  const [toast, setToast] = useState('');
  const notify = (message: string) => { setToast(message); window.setTimeout(() => setToast(''), 3500); };
  return <div className="app">{view === 'home' && <Home onNavigate={setView} />}{view === 'admin' && <Admin onBack={() => setView('home')} notify={notify} />}{view === 'portal' && <Portal onBack={() => setView('home')} notify={notify} />}{view === 'kiosk' && <Kiosk onBack={() => setView('home')} notify={notify} />}{toast && <div className="toast">{toast}</div>}</div>;
}

function Brand() { return <div className="brand"><div className="brand-mark">RBF</div><span>GHOST VAULT</span></div>; }
function Header({ onBack }: { onBack?: () => void }) { return <header className="topbar"><div style={{display:'flex',alignItems:'center',gap:18}}>{onBack && <button className="button ghost" onClick={onBack} style={{padding:'8px 10px'}}><ArrowLeft size={16}/></button>}<Brand /></div><div className="top-actions"><span className="status-dot"><i className="dot"/> SYSTEMS ONLINE</span><span className="muted" style={{fontSize:12}}>26 AUG 2026</span></div></header>; }

function Home({ onNavigate }: { onNavigate: (v: View) => void }) { const [showJoin,setShowJoin]=useState(false); return <><Header/><main className="home"><div className="home-hero"><div><div className="kicker">RBF FITNESS // COMMAND OS</div><h1>Train harder.<br/><em>Move smarter.</em></h1><p className="home-copy">One connected operating system for your gym. Run your floor, empower your warriors, and keep every rep accountable.</p><div style={{display:'flex',gap:10,marginTop:30,flexWrap:'wrap'}}><button className="button primary" onClick={() => onNavigate('admin')}><LayoutDashboard size={16}/> Open command center</button><button className="button ghost" onClick={() => onNavigate('kiosk')}><Radio size={16}/> Launch kiosk</button></div></div><div className="entry-grid"><div className="entry" onClick={() => onNavigate('admin')}><div className="entry-copy"><b>Supreme Command</b><span>Approvals, revenue, warriors, intelligence</span></div><ChevronRight size={18} color="#e9b949"/></div><div className="entry" onClick={() => onNavigate('portal')}><div className="entry-copy"><b>Warrior Portal</b><span>Digital pass, plans, analytics, attendance</span></div><ChevronRight size={18} color="#36d8d3"/></div><div className="entry" onClick={() => onNavigate('kiosk')}><div className="entry-copy"><b>AI Kiosk Terminal</b><span>Scan. Verify. Welcome. Repeat.</span></div><ChevronRight size={18} color="#ff5c68"/></div><div className="entry" onClick={() => setShowJoin(true)}><div className="entry-copy"><b>Join RBF</b><span>Start your application for membership</span></div><ChevronRight size={18} color="#55d98a"/></div></div></div><div style={{display:'flex',gap:28,color:'#718096',fontSize:11,letterSpacing:'.08em',textTransform:'uppercase'}}><span><ShieldCheck size={14} style={{verticalAlign:'middle',marginRight:5}}/> Secure vault</span><span><Radio size={14} style={{verticalAlign:'middle',marginRight:5}}/> Live telemetry</span><span><Zap size={14} style={{verticalAlign:'middle',marginRight:5}}/> AI ready</span></div></main>{showJoin&&<RegistrationModal onClose={()=>setShowJoin(false)} onSaved={()=>{setShowJoin(false);}}/>}</>; }

function Admin({ onBack, notify }: { onBack: () => void; notify: (m: string) => void }) {
  const { db, refresh, update } = useDB();
  const [tab,setTab]=useState<AdminTab>('overview');
  const [showExpense,setShowExpense]=useState(false);

  const load = useCallback(() => { refresh(); }, [refresh]);
  usePolling(load, 10000);

  const members = db.members;
  const pending = db.pending_approvals.filter(x => x.status === 'PENDING');
  const billing = db.billing;
  const attendance = db.attendance_logs;
  const expenses = db.expenses;

  const revenue = billing.reduce((s,x)=>s+(x.paid??0),0);
  const expenseTotal = expenses.reduce((s,x)=>s+(x.amount??0),0);
  const active = members.filter(m=>daysLeft(m.expiry_date)>0).length;
  const present = attendance.filter(x=>x.punch_in_time&&new Date(x.punch_in_time).toDateString()===new Date().toDateString()&&!x.punch_out_time).length;

  const approve = (id: number) => {
    const item = pending.find(x => x.id === id);
    if (!item) return;
    update(d => {
      const memberId = `SRB929${String(d.counters.pending).padStart(5, '0')}`;
      const passcode = String(Math.floor(1000 + Math.random() * 9000));
      const now = new Date();
      const expiry = new Date(now); expiry.setDate(expiry.getDate() + 30);
      d.members.unshift({
        member_id: memberId,
        name: item.name,
        phone: item.mobile,
        dob: item.dob,
        gender: item.gender,
        joining_date: now.toISOString().slice(0, 10),
        package: 'Monthly',
        expiry_date: expiry.toISOString().slice(0, 10),
      });
      d.ghost_vault.push({ member_id: memberId, passcode });
      d.billing.unshift({
        id: d.counters.billing,
        member_id: memberId,
        package_name: 'Monthly',
        amount: 1500,
        discount: 0,
        paid: 1500,
        due: 0,
        payment_date: now.toISOString().slice(0, 10),
        expiry_date: expiry.toISOString().slice(0, 10),
      });
      d.counters.billing++;
      d.counters.pending++;
      const approval = d.pending_approvals.find(a => a.id === id);
      if (approval) approval.status = 'APPROVED';
    });
    notify(`${item.name || 'Warrior'} approved and vault created.`);
  };

  return <><Header onBack={onBack}/><div className="shell"><aside className="sidebar"><div className="side-label">Command center</div><nav className="nav">{([['overview','Overview',LayoutDashboard],['approvals','Approvals',Bell],['members','Warriors',Users],['billing','Billing',CreditCard],['expenses','Expenses',Wallet],['ai','Omni AI Hub',Sparkles]] as const).map(([key,label,Icon])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={16}/>{label}{key==='approvals'&&pending.length>0&&<span className="pill red" style={{marginLeft:'auto',padding:'3px 6px'}}>{pending.length}</span>}</button>)}</nav><div style={{marginTop:40,padding:'0 14px',color:'#607083',fontSize:11,lineHeight:1.6}}>Live sync active<br/><span style={{color:'#36d8d3'}}>Auto-refresh every 10s</span></div></aside><main className="content">{tab==='overview'&&<Overview members={members} pending={pending} billing={billing} attendance={attendance} revenue={revenue} expenseTotal={expenseTotal} active={active} present={present} onApprovals={()=>setTab('approvals')} onRefresh={load}/>} {tab==='approvals'&&<Approvals pending={pending} onApprove={approve}/>} {tab==='members'&&<Members members={members}/>} {tab==='billing'&&<BillingView billing={billing} members={members}/>} {tab==='expenses'&&<Expenses expenses={expenses} onAdd={()=>setShowExpense(true)} onRefresh={load}/>} {tab==='ai'&&<AIHub members={members} notify={notify}/>}</main></div>{showExpense&&<ExpenseModal onClose={()=>setShowExpense(false)} onSaved={()=>{setShowExpense(false);notify('Expense logged.');}}/>}</>;
}

function Overview(p:{members:Member[];pending:PendingApproval[];billing:Billing[];attendance:AttendanceLog[];revenue:number;expenseTotal:number;active:number;present:number;onApprovals:()=>void;onRefresh:()=>void}) { const recent=p.attendance.slice(0,5); return <><div className="page-head"><div><p className="eyebrow">Supreme command center</p><h1 className="title">Good morning, Commander.</h1><p className="sub">Your gym pulse, in one clear view.</p></div><button className="button" onClick={p.onRefresh}><RefreshCw size={15}/> Sync now</button></div><div className="grid stats"><Stat icon={Users} label="Total warriors" value={p.members.length} foot={`${p.active} active memberships`} color="var(--gold)"/><Stat icon={CircleDollarSign} label="Collected revenue" value={money(p.revenue)} foot={`${money(p.revenue-p.expenseTotal)} net position`} color="var(--green)"/><Stat icon={Activity} label="On floor now" value={p.present} foot="Live attendance" color="var(--cyan)"/><Stat icon={Bell} label="Pending review" value={p.pending.length} foot="Needs your attention" color="var(--red)"/></div><div className="grid layout-2"><div className="card"><div className="card-title">Live floor activity <span>Today</span></div>{recent.length?<div className="activity">{recent.map((x)=><div className="activity-item" key={x.id}><div className="activity-icon"><UserCheck size={15}/></div><div className="activity-copy"><b>{x.member_id}</b> {x.punch_out_time?'completed a session':'checked in'}<small>{x.punch_in_time?new Date(x.punch_in_time).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'}):'Just now'} · {x.status||'verified'}</small></div><span className={x.punch_out_time?'pill':'pill gold'} style={{marginLeft:'auto'}}>{x.punch_out_time?'OUT':'IN'}</span></div>)}</div>:<div className="empty">No check-ins logged yet.</div>}</div><div className="card"><div className="card-title">Verification queue <span>Action required</span></div>{p.pending.slice(0,4).map(x=><div className="activity-item" style={{marginBottom:16}} key={x.id}><div className="activity-icon" style={{color:'var(--gold)'}}><Clock3 size={15}/></div><div className="activity-copy"><b>{x.name||'Unnamed applicant'}</b><small>{x.mobile} · {x.created_at?new Date(x.created_at).toLocaleDateString():'Recently'}</small></div><span className="pill red" style={{marginLeft:'auto'}}>NEW</span></div>)}{!p.pending.length&&<div className="empty">All caught up.</div>}{p.pending.length>0&&<button className="button ghost" onClick={p.onApprovals} style={{width:'100%',justifyContent:'center',marginTop:8}}>Review queue <ArrowRight size={14}/></button>}</div></div></>; }
function Stat({icon:Icon,label,value,foot,color}:{icon:typeof Users;label:string;value:string|number;foot:string;color:string}){return <div className="card stat" style={{'--accent':color} as CSSProperties}><div className="stat-top"><span>{label}</span><Icon size={17} color={color}/></div><div className="stat-value">{value}</div><div className="stat-foot" style={{color}}>{foot}</div></div>}

function Approvals({pending,onApprove}:{pending:PendingApproval[];onApprove:(id:number)=>void}){return <><div className="page-head"><div><p className="eyebrow">Smart verification queue</p><h1 className="title">New warriors</h1><p className="sub">Review applications and open their Ghost Vault.</p></div></div><div className="card"><div className="toolbar"><div className="card-title" style={{margin:0}}>Awaiting commander review <span>{pending.length} requests</span></div><button className="button"><FileText size={15}/> Export queue</button></div>{pending.length?<div className="table-wrap"><table className="table"><thead><tr><th>Applicant</th><th>Contact</th><th>Goal</th><th>Received</th><th></th></tr></thead><tbody>{pending.map(x=><tr key={x.id}><td><b>{x.name||'Unnamed'}</b><div className="muted">#{String(x.id).padStart(4,'0')}</div></td><td>{x.mobile}<div className="muted">{x.email||'No email'}</div></td><td>{x.goal||'General fitness'}</td><td>{x.created_at?new Date(x.created_at).toLocaleDateString():'—'}</td><td><button className="button primary" onClick={()=>onApprove(x.id)}><Check size={14}/> Approve</button></td></tr>)}</tbody></table></div>:<div className="empty">No pending applications. The queue is clear.</div>}</div></>}
function Members({members}:{members:Member[]}){const [q,setQ]=useState('');const filtered=members.filter(x=>(x.name||'').toLowerCase().includes(q.toLowerCase())||x.member_id.toLowerCase().includes(q.toLowerCase())||x.phone.includes(q));return <><div className="page-head"><div><p className="eyebrow">Cloud database manager</p><h1 className="title">Warrior directory</h1><p className="sub">Every member, one living record.</p></div></div><div className="card"><div className="toolbar"><div className="card-title" style={{margin:0}}>Registered warriors <span>{filtered.length} shown</span></div><div style={{position:'relative'}}><Search size={14} color="#728297" style={{position:'absolute',left:12,top:12}}/><input className="search" style={{paddingLeft:34}} placeholder="Search name or ID" value={q} onChange={e=>setQ(e.target.value)}/></div></div>{filtered.length?<div className="table-wrap"><table className="table"><thead><tr><th>Warrior</th><th>Phone</th><th>Package</th><th>Expires</th><th>Status</th></tr></thead><tbody>{filtered.map(x=><tr key={x.member_id}><td><b>{x.name||'Unknown'}</b><div className="muted">{x.member_id}</div></td><td>{x.phone}</td><td>{x.package||'—'}</td><td>{x.expiry_date||'—'}</td><td><span className={daysLeft(x.expiry_date)>0?'pill':'pill red'}>{daysLeft(x.expiry_date)>0?'ACTIVE':'EXPIRED'}</span></td></tr>)}</tbody></table></div>:<div className="empty">No warriors found.</div>}</div></>}
function BillingView({billing,members}:{billing:Billing[];members:Member[]}){const name=(id:string|null)=>members.find(m=>m.member_id===id)?.name||id||'Unknown';return <><div className="page-head"><div><p className="eyebrow">Smart billing gateway</p><h1 className="title">Financial ledger</h1><p className="sub">Invoices, collections, and due amounts at a glance.</p></div><button className="button primary"><CreditCard size={15}/> Create invoice</button></div><div className="grid stats"><Stat icon={CircleDollarSign} label="Gross billed" value={money(billing.reduce((s,x)=>s+(x.amount??0),0))} foot="All invoices" color="var(--gold)"/><Stat icon={CheckCircle2} label="Collected" value={money(billing.reduce((s,x)=>s+(x.paid??0),0))} foot="Payments received" color="var(--green)"/><Stat icon={Clock3} label="Outstanding" value={money(billing.reduce((s,x)=>s+(x.due??0),0))} foot="Needs follow-up" color="var(--red)"/><Stat icon={FileText} label="Invoices" value={billing.length} foot="Total records" color="var(--cyan)"/></div><div className="card"><div className="table-wrap"><table className="table"><thead><tr><th>Invoice</th><th>Warrior</th><th>Package</th><th>Amount</th><th>Paid</th><th>Due</th><th></th></tr></thead><tbody>{billing.map(x=><tr key={x.id}><td>INV-{String(x.id).padStart(5,'0')}</td><td><b>{name(x.member_id)}</b><div className="muted">{x.member_id}</div></td><td>{x.package_name||'—'}</td><td>{money(x.amount)}</td><td style={{color:'var(--green)'}}>{money(x.paid)}</td><td style={{color:(x.due??0)>0?'var(--red)':'var(--green)'}}>{money(x.due)}</td><td><button className="button ghost" style={{padding:'7px 9px'}}><FileText size={14}/></button></td></tr>)}</tbody></table></div>{!billing.length&&<div className="empty">No billing records yet.</div>}</div></>}
function Expenses({expenses,onAdd,onRefresh}:{expenses:Expense[];onAdd:()=>void;onRefresh:()=>void}){return <><div className="page-head"><div><p className="eyebrow">Operating costs</p><h1 className="title">Expense tracker</h1><p className="sub">Know where every rupee goes.</p></div><button className="button primary" onClick={onAdd}><Wallet size={15}/> Log expense</button></div><div className="card"><div className="toolbar"><div className="card-title" style={{margin:0}}>Recent expenses</div><button className="button ghost" onClick={onRefresh}><RefreshCw size={14}/></button></div><table className="table"><thead><tr><th>Description</th><th>Date</th><th>Amount</th></tr></thead><tbody>{expenses.map(x=><tr key={x.id}><td>{x.expense_name||'General expense'}</td><td>{x.expense_date||'—'}</td><td style={{color:'var(--red)'}}>{money(x.amount)}</td></tr>)}</tbody></table>{!expenses.length&&<div className="empty">No expenses logged.</div>}</div></>}

function ExpenseModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [name,setName]=useState('');const [amount,setAmount]=useState('');const { update } = useDB();const save=(e:FormEvent)=>{e.preventDefault();update(d=>{d.expenses.unshift({id:d.counters.expense,expense_name:name,amount:Number(amount),expense_date:todayStr()});d.counters.expense++});onSaved()};return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">New ledger entry</p><h2 style={{margin:0}}>Log expense</h2></div><button type="button" className="close" onClick={onClose}><X/></button></div><div className="form-grid"><div className="field full"><label>Description</label><input required value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Electricity bill"/></div><div className="field"><label>Amount</label><input required type="number" min="0" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0"/></div></div><div style={{display:'flex',justifyContent:'flex-end',gap:10,marginTop:22}}><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button primary">Save expense</button></div></form></div>}

function RegistrationModal({onClose,onSaved}:{onClose:()=>void;onSaved:()=>void}){const [form,setForm]=useState({name:'',mobile:'',email:'',dob:'',goal:''});const { update } = useDB();const updateField=(key:keyof typeof form)=>(e:ChangeEvent<HTMLInputElement|HTMLSelectElement>)=>setForm(x=>({...x,[key]:e.target.value}));const save=(e:FormEvent)=>{e.preventDefault();update(d=>{d.pending_approvals.push({id:d.counters.pending,name:form.name,mobile:form.mobile,email:form.email,dob:form.dob,address:null,status:'PENDING',created_at:new Date().toISOString(),gender:null,goal:form.goal});d.counters.pending++});onSaved()};return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><p className="eyebrow">New warrior application</p><h2 style={{margin:0}}>Start your RBF journey</h2><p className="sub">Your application goes to the commander for review.</p></div><button type="button" className="close" onClick={onClose}><X/></button></div><div className="form-grid"><div className="field"><label>Full name</label><input required value={form.name} onChange={updateField('name')} placeholder="Your name"/></div><div className="field"><label>Mobile</label><input required value={form.mobile} onChange={updateField('mobile')} placeholder="10-digit number"/></div><div className="field"><label>Date of birth</label><input required type="date" value={form.dob} onChange={updateField('dob')}/></div><div className="field"><label>Email</label><input type="email" value={form.email} onChange={updateField('email')} placeholder="you@example.com"/></div><div className="field full"><label>Primary goal</label><select required value={form.goal} onChange={updateField('goal')}><option value="">Choose a goal</option><option>Build muscle</option><option>Lose fat</option><option>Improve strength</option><option>General fitness</option></select></div></div><div style={{display:'flex',justifyContent:'flex-end',gap:10,marginTop:22}}><button type="button" className="button ghost" onClick={onClose}>Cancel</button><button className="button primary">Submit application</button></div></form></div>}

function AIHub({members,notify}:{members:Member[];notify:(m:string)=>void}){const [member,setMember]=useState('');const [goal,setGoal]=useState('Build a balanced 4-day strength program with warm-ups and progression.');const [plan,setPlan]=useState<{title:string;days:string[];notes:string}|null>(null);const generate=()=>{const target=members.find(m=>m.member_id===member)?.name||'your warrior';setPlan({title:`${target}'s Strength Protocol`,days:['Day 01 · Upper push — chest, shoulders, triceps','Day 02 · Lower strength — quads, hamstrings, core','Day 03 · Recovery — mobility and 25 min zone 2','Day 04 · Upper pull — back, biceps, rear delts'],notes:'Start every session with 8 minutes of movement prep. Add one rep before adding load. Sleep 7–8 hours and hydrate consistently.'});notify('AI plan drafted. Review before assigning.');};return <><div className="page-head"><div><p className="eyebrow">Built-in AI coach</p><h1 className="title">Omni AI Hub</h1><p className="sub">Draft a plan, then assign it to a warrior.</p></div><span className="pill">AI READY</span></div><div className="grid layout-2"><div className="card"><div className="field"><label>Assign to warrior</label><select value={member} onChange={e=>setMember(e.target.value)}><option value="">Select a warrior</option>{members.map(m=><option key={m.member_id} value={m.member_id}>{m.name||m.member_id} · {m.member_id}</option>)}</select></div><div className="field" style={{marginTop:16}}><label>Coach prompt</label><textarea value={goal} onChange={e=>setGoal(e.target.value)}/></div><button className="button cyan" style={{marginTop:18}} onClick={generate}><Sparkles size={15}/> Generate training plan</button></div><div className="card">{plan?<><div className="card-title">{plan.title}<span>Draft</span></div><div className="activity">{plan.days.map(x=><div className="activity-item" key={x}><div className="activity-icon"><Dumbbell size={15}/></div><div className="activity-copy">{x}</div></div>)}</div><p className="sub" style={{lineHeight:1.6}}>{plan.notes}</p><button className="button primary" style={{marginTop:10}} onClick={()=>notify('Plan assigned to the selected warrior.')}>Assign plan</button></>:<div className="empty"><Sparkles size={24} style={{marginBottom:10}}/><br/>Your generated plan will appear here.</div>}</div></div></>}

function Portal({onBack,notify}:{onBack:()=>void;notify:(m:string)=>void}){const { db } = useDB();const [memberId,setMemberId]=useState('');const [passcode,setPasscode]=useState('');const [member,setMember]=useState<Member|null>(null);const [loginError,setLoginError]=useState('');const login=(e:FormEvent)=>{e.preventDefault();setLoginError('');const entry=db.ghost_vault.find(x=>x.member_id===memberId.trim()&&x.passcode===passcode.trim());if(!entry){setLoginError('Warrior ID or passcode not recognised.');return}const found=db.members.find(m=>m.member_id===entry.member_id);if(found)setMember(found);else setLoginError('Your vault profile could not be loaded.');};return <><Header onBack={onBack}/>{!member?<main className="portal-login"><div className="card"><p className="eyebrow">Warrior portal</p><h1 className="title">Enter the vault.</h1><p className="sub">Use the ID and secret passcode sent when your membership was approved.</p><form onSubmit={login} style={{marginTop:26}}><div className="field"><label>Warrior ID</label><input required value={memberId} onChange={e=>setMemberId(e.target.value.toUpperCase())} placeholder="e.g. SRB92900001"/></div><div className="field" style={{marginTop:14}}><label>Secret passcode</label><input required type="password" inputMode="numeric" maxLength={4} value={passcode} onChange={e=>setPasscode(e.target.value)} placeholder="4 digits"/></div>{loginError&&<p className="error" style={{fontSize:12}}>{loginError}</p>}<button className="button cyan" style={{width:'100%',justifyContent:'center',marginTop:20}}><LogIn size={15}/> Unlock my portal</button></form><p className="muted" style={{fontSize:11,marginTop:16,textAlign:'center'}}>Demo: SRB92900001 / 1234 or SRB92900002 / 5678</p></div></main>:<MemberPortal member={member} onLogout={()=>setMember(null)} notify={notify}/>}</>}
function MemberPortal({member,onLogout,notify}:{member:Member;onLogout:()=>void;notify:(m:string)=>void}){return <main className="portal"><div className="portal-head"><div><p className="eyebrow">Welcome back, warrior</p><h1 className="title">{member.name||member.member_id}</h1><p className="sub">{member.member_id} · {member.package||'Active member'}</p></div><button className="button ghost" onClick={onLogout}><LogOut size={15}/> Lock vault</button></div><div className="grid portal-grid"><div className="card" style={{textAlign:'center'}}><div className="card-title">Digital gate pass <span>Scan at entrance</span></div><div className="qr"><QRCodeSVG value={member.member_id} size={190}/></div><p className="sub">Show this code to the AI kiosk</p></div><div className="card"><div className="card-title">Membership status <span className="pill">{daysLeft(member.expiry_date)>0?'ACTIVE':'EXPIRED'}</span></div><div style={{display:'flex',justifyContent:'space-between',alignItems:'end'}}><div><div className="stat-value" style={{color:'var(--cyan)'}}>{daysLeft(member.expiry_date)}</div><div className="result-label">days remaining</div></div><Target size={42} color="var(--gold)"/></div><div className="progress"><i style={{width:`${Math.min(100,Math.max(4,daysLeft(member.expiry_date)/30*100))}%`}}/></div><div style={{display:'flex',justifyContent:'space-between',marginTop:14,fontSize:12}}><span className="muted">Started</span><b>{member.joining_date||'—'}</b><span className="muted">Expires</span><b>{member.expiry_date||'—'}</b></div></div></div><Calculators notify={notify}/></main>}
function Calculators({notify}:{notify:(m:string)=>void}){const [height,setHeight]=useState('175');const [weight,setWeight]=useState('75');const bmi=(Number(weight)/(Number(height)/100)**2||0).toFixed(1);const [oneRmWeight,setOneRmWeight]=useState('60');const [reps,setReps]=useState('8');const oneRm=(Number(oneRmWeight)*(1+Number(reps)/30)||0).toFixed(1);const [age,setAge]=useState('28');const bmr=(10*Number(weight)+6.25*Number(height)-5*Number(age)+5||0).toFixed(0);return <section style={{marginTop:32}}><div className="card-title">Performance lab <span>Personal analytics</span></div><div className="grid calc-grid"><div className="card"><div className="card-title"><BarChart3 size={16} color="var(--cyan)"/> BMI engine</div><div className="form-grid"><div className="field"><label>Height (cm)</label><input type="number" value={height} onChange={e=>setHeight(e.target.value)}/></div><div className="field"><label>Weight (kg)</label><input type="number" value={weight} onChange={e=>setWeight(e.target.value)}/></div></div><div className="calc-result">{bmi}</div><div className="result-label">{Number(bmi)<18.5?'Below range':Number(bmi)<25?'Healthy range':'Above range'}</div></div><div className="card"><div className="card-title"><Zap size={16} color="var(--gold)"/> 1RM estimator</div><div className="form-grid"><div className="field"><label>Weight (kg)</label><input type="number" value={oneRmWeight} onChange={e=>setOneRmWeight(e.target.value)}/></div><div className="field"><label>Reps</label><input type="number" value={reps} onChange={e=>setReps(e.target.value)}/></div></div><div className="calc-result">{oneRm} kg</div><div className="result-label">Estimated one-rep max</div></div><div className="card"><div className="card-title"><Activity size={16} color="var(--green)"/> BMR baseline</div><div className="field"><label>Age</label><input type="number" value={age} onChange={e=>setAge(e.target.value)}/></div><div className="calc-result">{bmr}</div><div className="result-label">Estimated calories / day</div></div><div className="card"><div className="card-title"><DropletIcon/> Hydration target</div><div className="calc-result">{(Number(weight)*.035).toFixed(1)} L</div><div className="result-label">Daily baseline · add 500ml per workout</div></div><div className="card"><div className="card-title"><HeartIcon/> Cardio HR zone</div><div className="calc-result">{Math.round(208-.7*Number(age))}</div><div className="result-label">Estimated max heart rate</div></div><div className="card"><div className="card-title"><Calculator size={16} color="var(--blue)"/> Macro guide</div><div className="calc-result">{Number(weight)*2}g</div><div className="result-label">Daily protein target</div><button className="button ghost" style={{marginTop:14}} onClick={()=>notify('Macro guide uses your current body weight.')}>View breakdown <ArrowRight size={13}/></button></div></div></section>}
function DropletIcon(){return <span style={{color:'var(--cyan)'}}>◈</span>} function HeartIcon(){return <span style={{color:'var(--red)'}}>♡</span>}

function Kiosk({onBack,notify}:{onBack:()=>void;notify:(m:string)=>void}){const { db, update } = useDB();const [code,setCode]=useState('');const [message,setMessage]=useState('');const [logs,setLogs]=useState<{id:string;name:string;action:string;time:string}[]>([]);const scan=(e:FormEvent)=>{e.preventDefault();if(!code.trim())return;const data=db.members.find(m=>m.member_id===code.trim().toUpperCase());if(!data){setMessage('ACCESS DENIED · ID NOT FOUND');notify('Warrior ID not found.');setCode('');return}const today=todayStr();const existing=db.attendance_logs.find(x=>x.member_id===data.member_id&&x.punch_in_time&&x.punch_in_time.slice(0,10)===today&&!x.punch_out_time);let action='CHECK-IN';update(d=>{if(existing){const rec=d.attendance_logs.find(x=>x.id===existing.id);if(rec){rec.punch_out_time=new Date().toISOString();rec.status='CHECKED_OUT'}action='CHECK-OUT'}else{d.attendance_logs.unshift({id:d.counters.attendance,member_id:data.member_id,punch_in_time:new Date().toISOString(),punch_out_time:null,status:'CHECKED_IN'});d.counters.attendance++}});setMessage(`${action} · ${data.name||data.member_id}`);setLogs(x=>[{id:data.member_id,name:data.name||data.member_id,action,time:new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})},...x].slice(0,6));setCode('');};return <main className="kiosk"><div className="kiosk-inner"><div className="kiosk-head"><Brand/><div style={{display:'flex',alignItems:'center',gap:15}}><span className="status-dot"><i className="dot"/> SCANNER READY</span><button className="button ghost" onClick={onBack}><ArrowLeft size={15}/> Exit</button></div></div><div className="scan-box"><p className="kicker">RBF AI KIOSK // GATE 01</p><h1 className="title">Scan to enter.</h1><p className="sub">Present your QR pass or type your Warrior ID.</p><div className="scan-frame"><div className="scan-line"/><Radio size={48} strokeWidth={1}/></div><form onSubmit={scan}><input autoFocus className="kiosk-input" value={code} onChange={e=>setCode(e.target.value)} placeholder="WARRIOR ID"/></form>{message&&<p className={message.includes('DENIED')?'error':'success'} style={{fontSize:13,letterSpacing:'.08em',marginTop:20}}>{message}</p>}<div className="log-list" style={{textAlign:'left'}}>{logs.length>0&&<p className="eyebrow" style={{margin:'18px 0 0'}}>Live action log</p>}{logs.map(x=><div className="log" key={x.id+x.time}><span><b>{x.name}</b> · {x.action}</span><span>{x.time}</span></div>)}</div></div></div></main>}
